apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot-parallel-job
spec:
#5 pods can be created, not more than that.
  parallelism: 5
#comp 10 means it should be finished 10 times.
#every pod will do the job 2 times.
  completions: 10
  template:
    metadata:
      labels:
        app: oneshot-parallel-job-pod
    spec:
      containers:
      - args:
        - --keygen-enable
        - --keygen-exit-on-complete
        - --keygen-num-to-gen
        - "10"
        image: gcr.io/kuar-demo/kuard-amd64:1
        name: oneshot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      restartPolicy: OnFailure

